name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: quay.io/dvulpe/docker-bazelisk:v1.7.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
      - name: bazel cache
        uses: actions/cache@v2
        with:
          path: /github/home/.bazel_cache
          key: ${{ runner.os }}-${{ hashFiles('WORKSPACE') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('WORKSPACE') }}
      - name: Run tests
        run: bazel test //...
