name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
      - run: go install github.com/bazelbuild/bazelisk@latest
      - name: bazel cache
        uses: actions/cache@v4
        with:
          path: /github/home/.bazel_cache
          key: ${{ runner.os }}-${{ hashFiles('WORKSPACE') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('WORKSPACE') }}
      - name: Build all examples
        run: bazelisk build //examples/...
      - name: Run tests
        run: bazelisk test //...
