name: Release

on:
    workflow_dispatch:
      inputs:
        releaseType:
          description: "Release Type"
          required: true
          default: 'patch'
          type: choice
          options:
          - major
          - minor
          - patch
        description:
          description: 'Description'
          required: true
          type: string

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    env:
      TYPE: ${{ inputs.releaseType }}
      DESCRIPTION: ${{ inputs.description }}
    steps:
      - run: |
          echo "Release type: $TYPE"
          echo "Description:"
          echo $DESCRIPTION
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
            echo "${{steps.build_changelog.outputs.changelog}}"