name: Release

on:
    workflow_dispatch:
      inputs:
        releaseType:
          description: "Release Type"
          required: true
          default: 'patch'
          type: choice
          options:
          - major
          - minor
          - patch
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
          - info
          - warning
          - debug
        tags:
          description: 'Test scenario tags'
          required: false
          type: boolean

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    env:
      LEVEL: ${{ inputs.logLevel }}
      TAGS: ${{ inputs.tags }}
      TYPE: ${{ inputs.releaseType }}
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Release type: $TYPE"