name: Test Dev Container Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build-devcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: src
      - name: Build Image
        run: |
          pushd src/.github/workflows/devcontainer
          docker build -t bazel-terraform-rules-devcontainer .
          popd  